samples:
  - HSC_1
  - HSC_2
  - HSC_3
directories:
  - results/preprocess_01/01_FastQC_raw_data
  - results/preprocess_01/02_UMI_extraction
  - results/preprocess_01/02_UMI_extraction/Read2s
  - results/preprocess_01/03_trimmed_data
  - results/preprocess_01/03_trimmed_data/unzipped
  - results/preprocess_01/04_FastQC_trimmed_data
  - results/preprocess_01/05_sortmernaed_data
  - results/preprocess_01/05_sortmernaed_data/zipped
  - results/preprocess_01/06_FQScreen
  - results/preprocess_01/07_star_aligned
  - results/preprocess_01/08_umi_deduplicated
  - results/preprocess_01/09_picard_markdup
  - results/preprocess_01/10_featureCounts
  - results/preprocess_01/11_TinScore
  - results/preprocess_01/12_GeneBodyCov
  - logs/01_FastQC_rawdata
  - logs/02_UMI_extraction
  - logs/03_trimming
  - logs/04_FastQC_trimmed
  - logs/05_sortmerna
  - logs/06_FQScreen
  - logs/07_staraligner
  - logs/08_UMI_deduplication
  - logs/09_picard_markdup
  - logs/10_featureCounts
trimming_params:
    quality: 30
    length: 30
    stringency: 2
sortmerna_ref:
  - /mnt/groupMansuy/kerem/tasks/longrna/genome/rRNA_databases/silva-euk-28s-id98.fasta
  - /mnt/groupMansuy/kerem/tasks/longrna/genome/rRNA_databases/silva-euk-18s-id95.fasta
  - /mnt/groupMansuy/kerem/tasks/longrna/genome/rRNA_databases/silva-arc-16s-id95.fasta
  - /mnt/groupMansuy/kerem/tasks/longrna/genome/rRNA_databases/silva-arc-23s-id98.fasta
  - /mnt/groupMansuy/kerem/tasks/longrna/genome/rRNA_databases/silva-bac-16s-id90.fasta
  - /mnt/groupMansuy/kerem/tasks/longrna/genome/rRNA_databases/silva-bac-23s-id98.fasta
  - /mnt/groupMansuy/kerem/tasks/longrna/genome/rRNA_databases/rfam-5.8s-database-id98.fasta
  - /mnt/groupMansuy/kerem/tasks/longrna/genome/rRNA_databases/rfam-5s-database-id98.fasta
fastq_screen_conf: "/mnt/IM/groupMansuy/kerem/auxiliary/conf/fastq_screen.conf"
star_genome_dir: "/mnt/groupMansuy/kerem/auxiliary/genome/staridx"
GTF_file: "/mnt/groupMansuy/kerem/auxiliary/genome/GCF_000001635.27_GRCm39_genomic.gtf"
bed_file: "/mnt/groupMansuy/kerem/auxiliary/genome/GRCm39_genomic.bed12"